### ISSUE TITLE
Migrate docs from GitHub Pages to ReadTheDocs

### ISSUE THREAD

**Issue by bkeryan** [ni/measurementlink-python#431]
## Problem to Solve

GitHub Pages [only displays docs for a single branch of the repository](https://www.github.com/orgs/community/discussions/21582). This means that the docs on the web only cover the most recent release, not previous preleases or pre-releases for the upcoming release.

## Proposed Solution

Migrate from GitHub Pages to ReadTheDocs.

## Tasks
- [x] Follow the [ReadTheDocs tutorial](https://docs.readthedocs.io/en/stable/tutorial/index.html).
  - The config will be similar to [nidaqmx-python](https://github.com/ni/nidaqmx-python/blob/master/.readthedocs.yml), except we don't need to add a `docs` extra since we have a `docs` dependency group.
- [x] Set up GitHub Pages to redirect to ReadTheDocs (done by setting the RTD domain as a custom domain).
- [x] Set up ReadTheDocs to redirect the prefix / -> /$lang/$version to avoid breaking links to the old site.

[AB#2541821](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2541821)
